import Link from 'next/link';
import {articles} from '../lib/articles';

const focus=[['Γαστρεντερικό & IBS','Συμπτώματα, ανοχές, καθημερινότητα και πρακτικές λύσεις χωρίς άσκοπους αποκλεισμούς.'],['Απώλεια βάρους','Σταθερή αλλαγή συνηθειών με ρεαλιστικούς στόχους και εξατομικευμένη παρακολούθηση.'],['Μεταβολική υγεία','Διατροφή γύρω από σάκχαρο, ινσουλινοαντίσταση και τον συνολικό τρόπο ζωής.'],['Γυναίκα & κύκλος ζωής','Εγκυμοσύνη, θηλασμός, εμμηνόπαυση και περίοδοι όπου οι διατροφικές ανάγκες αλλάζουν.'],['Αθλητική διατροφή','Ενέργεια, γεύματα γύρω από την άσκηση και πρακτική οργάνωση.'],['Παιδική διατροφή','Εκπαίδευση παιδιού και οικογένειας χωρίς ενοχές και χωρίς «μάχη» γύρω από το φαγητό.']];
const values=[['01','Επιστήμη','Ενημέρωση που στηρίζεται σε εκπαίδευση και σύγχρονη γνώση.'],['02','Εξατομίκευση','Το πλάνο προσαρμόζεται στον άνθρωπο, όχι το αντίστροφο.'],['03','Πρακτικότητα','Οι οδηγίες πρέπει να εφαρμόζονται και σε δύσκολες ημέρες.'],['04','Συνέπεια','Η πρόοδος χτίζεται με μικρές αλλαγές που μπορούν να διατηρηθούν.']];
const blogImages=['blog-veg','blog-waist','blog-sport'];
export default function Home(){return <main>
<section className="hero hero-modern"><div className="hero-orb orb-one"/><div className="hero-orb orb-two"/><div className="hero-objects" aria-hidden="true"><span className="float-object o1">Ω3</span><span className="float-object o2">Fe</span><span className="float-object o3">♥</span><span className="float-object o4">Mg</span><span className="float-object o5">+</span></div><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow">CORRECT EAT · ΔΙΑΙΤΟΛΟΓΟΣ – ΔΙΑΤΡΟΦΟΛΟΓΟΣ</div><h1>Η διατροφή σου.<br/><em>Η δική σου καθημερινότητα.</em></h1><p className="hero-lead">Εξατομικευμένη διατροφική υποστήριξη από την Ευδοξία Τσιτάκη, με επιστημονική προσέγγιση, πρακτική εφαρμογή και χώρο για την πραγματική ζωή.</p><div className="hero-actions"><Link className="btn primary btn-large" href="/epikoinonia#rantevou">Κλείσε ραντεβού ↗</Link><Link className="btn glass-btn btn-large" href="/sxetika-me-emena">Γνώρισε την προσέγγισή μου</Link></div><div className="hero-proof"><span className="proof-dot"/> Επιστημονική προσέγγιση <span className="sep"/> Εξατομίκευση <span className="sep"/> Πρακτικότητα</div></div><div className="hero-visual"><div className="hero-photo-large"><img src="/evdoxia.jpg" alt="Ευδοξία Τσιτάκη – Διαιτολόγος Διατροφολόγος"/></div><div className="floating-note glass-surface"><small>Η φιλοσοφία μου</small><strong>Δεν κυνηγάμε την τελειότητα.<br/>Χτίζουμε συνέπεια.</strong></div><div className="floating-badge">✓ <span>Προσωπική<br/>προσέγγιση</span></div></div></div></section>

<section className="stat-band"><div className="container stats-grid"><div className="stat-card"><span className="stat-index">01</span><b>BSc Dietetics</b><span>Queen Margaret University, Edinburgh</span></div><div className="stat-card"><span className="stat-index">02</span><b>Master Practitioner</b><span>Eating Disorders & Obesity</span></div><div className="stat-card"><span className="stat-index">03</span><b>Μεταβολομική</b><span>Κλινική εφαρμογή σε αυτοάνοσα & χρόνια νοσήματα</span></div><div className="stat-card"><span className="stat-index">04</span><b>Γαστρεντερικό</b><span>Διατροφή & μικροβίωμα</span></div><div className="stat-card"><span className="stat-index">05</span><b>Αρθρογραφία</b><span>Ενημέρωση μέσω blog & social media</span></div></div></section>

<section className="led-section"><div className="container"><div className="led-window"><div className="led-window-track"><span><i className="led-dot"/> CORRECT EAT</span><span>ΔΙΑΤΡΟΦΗ ΜΕ ΝΟΗΜΑ</span><span>ΕΞΑΤΟΜΙΚΕΥΜΕΝΗ ΠΡΟΣΕΓΓΙΣΗ</span><span>ΕΥΕΛΙΞΙΑ · ΣΥΝΕΠΕΙΑ · ΕΠΙΣΤΗΜΗ</span><span><i className="led-dot"/> CORRECT EAT</span><span>ΔΙΑΤΡΟΦΗ ΜΕ ΝΟΗΜΑ</span><span>ΕΞΑΤΟΜΙΚΕΥΜΕΝΗ ΠΡΟΣΕΓΓΙΣΗ</span><span>ΕΥΕΛΙΞΙΑ · ΣΥΝΕΠΕΙΑ · ΕΠΙΣΤΗΜΗ</span></div></div></div></section>

<section className="section intro-section"><div className="container intro-grid"><div><div className="eyebrow">Η δική μου προσέγγιση</div><h2>Δεν χρειάζεσαι περισσότερους κανόνες. Χρειάζεσαι ένα πλάνο που βγάζει νόημα.</h2></div><div><p className="large-copy">Η διατροφή είναι κομμάτι της καθημερινότητάς σου. Γι’ αυτό το πλάνο πρέπει να χωράει στις ώρες σου, στις προτιμήσεις σου, στις κοινωνικές σου στιγμές και στις πραγματικές σου ανάγκες.</p><p className="muted">Η δουλειά μας δεν τελειώνει όταν πάρεις ένα πρόγραμμα. Εκεί ξεκινά η ουσιαστική εφαρμογή.</p><Link className="text-link" href="/sxetika-me-emena">Δες την επαγγελματική μου διαδρομή →</Link></div></div></section>

<section className="section section-soft"><div className="container"><div className="section-head modern-head"><div><div className="eyebrow">Τομείς υποστήριξης</div><h2>Εξειδίκευση με ανθρώπινη ματιά.</h2></div><p>Κάθε ανάγκη έχει διαφορετική αφετηρία. Η προσέγγιση προσαρμόζεται στην εικόνα σου και αλλάζει μαζί με την πορεία σου.</p></div><div className="focus-grid">{focus.map(([title,text],i)=><Link className="focus-card" href="/ypiresies" key={title}><span className="focus-number">0{i+1}</span><div><h3>{title}</h3><p>{text}</p></div><span className="circle-arrow">↗</span></Link>)}</div></div></section>

<section className="section motion-stage"><div className="container"><div className="section-head modern-head"><div><div className="eyebrow">Η καθημερινότητα σε κίνηση</div><h2>Μικρές αλλαγές.<br/>Πιο σταθερή πορεία.</h2></div><p>Δεν χρειάζεται να αλλάξεις τα πάντα μαζί. Χρειάζεται να βρεις τι έχει τη μεγαλύτερη αξία για εσένα.</p></div><div className="motion-card"><div className="orbit"/><div className="orbit orbit-two"/><div className="motion-pill pill-a">Ενέργεια</div><div className="motion-pill pill-b">Κορεσμός</div><div className="motion-pill pill-c">Ρουτίνα</div><div className="motion-meter"><div className="meter-head"><span>Συνέπεια εβδομάδας</span><b>74%</b></div><div className="meter-bar"><div className="meter-fill"/></div></div></div></div></section>

<section className="section"><div className="container"><div className="section-head modern-head"><div><div className="eyebrow">Τι έχει σημασία</div><h2>Ο τρόπος που δουλεύουμε.</h2></div></div><div className="focus-grid">{values.map(([n,t,d])=><div className="focus-card" key={n}><span className="focus-number">{n}</span><div><h3>{t}</h3><p>{d}</p></div><span className="circle-arrow">✓</span></div>)}</div></div></section>

<section className="section split-feature"><div className="container feature-panel"><div className="feature-copy"><div className="eyebrow eyebrow-light">Τι θα πάρεις από τη συνεργασία</div><h2>Όχι απλώς ένα πρόγραμμα.<br/><em>Ένα σύστημα που μπορείς να εφαρμόσεις.</em></h2><p>Η εξατομίκευση σημαίνει να ξέρεις τι να κάνεις όταν η ημέρα δεν πάει όπως την είχες σχεδιάσει.</p><div className="check-list">{['Εξατομικευμένο πλάνο','Πρακτικές λύσεις για την καθημερινότητα','Δια ζώσης & online συνεδρίες','Συνεχής προσαρμογή ανάλογα με την πορεία'].map(x=><div key={x}><b>✓</b>{x}</div>)}</div><Link className="btn primary" href="/epikoinonia#rantevou">Ξεκίνα τη συνεργασία ↗</Link></div><div className="feature-quote"><span>“</span><p>Η συνέπεια δεν χτίζεται με περισσότερους κανόνες. Χτίζεται όταν η διατροφή γίνεται αρκετά ρεαλιστική ώστε να μπορείς να την ακολουθείς.</p><small>— Ευδοξία Τσιτάκη</small></div></div></section>

<section className="section articles-section"><div className="container"><div className="section-head modern-head"><div><div className="eyebrow">Correct Eat Journal</div><h2>Από το αρχείο του blog μου.</h2></div><Link className="btn ghost" href="/arthra">Όλα τα άρθρα ↗</Link></div><div className="article-grid-modern">{articles.slice(0,3).map((a,i)=><Link className="article-card-modern" href={`/arthra/${a.slug}`} key={a.slug}><div className={`article-visual ${blogImages[i]}`}><span>{a.category}</span></div><div className="article-body"><div className="article-meta">{a.date}</div><h3>{a.title}</h3><p>{a.excerpt}</p><span className="source-pill">Από το tsitakh.blogspot.com</span></div></Link>)}</div></div></section>

<section className="section social-section"><div className="container social-grid"><div className="social-copy"><div className="eyebrow">Instagram</div><h2>Και εκτός συνεδρίας, συνεχίζουμε την ενημέρωση.</h2><p>Σύντομα tips, εκπαιδευτικό περιεχόμενο και στιγμές από το Correct Eat.</p><a className="btn primary" href="https://www.instagram.com/correct_eat/" target="_blank" rel="noreferrer">@correct_eat στο Instagram ↗</a></div><div className="ig-wall"><a className="ig-tile ig-1" href="https://www.instagram.com/correct_eat/" target="_blank" rel="noreferrer"/><a className="ig-tile ig-2" href="https://www.instagram.com/correct_eat/" target="_blank" rel="noreferrer"/><a className="ig-tile ig-3" href="https://www.instagram.com/correct_eat/" target="_blank" rel="noreferrer"/></div></div></section>

<section className="section"><div className="container cta-modern"><div className="cta-glow"/><div className="eyebrow eyebrow-light">ΕΠΟΜΕΝΟ ΒΗΜΑ</div><h2>Η σωστή προσέγγιση ξεκινά από τη δική σου πραγματικότητα.</h2><p>Διάλεξε τον τρόπο συνεργασίας που σε εξυπηρετεί και ας οργανώσουμε το επόμενο βήμα.</p><Link className="btn ghost" href="/epikoinonia#rantevou">Κλείσε ραντεβού ↗</Link></div></section>
</main>}
